// <auto-generated />
using System;
using DataTierWebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataTierWebServer.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20240929093658_InialCreate")]
    partial class InialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("DataTierWebServer.Models.Account", b =>
                {
                    b.Property<uint>("AcctNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AcctNo");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AcctNo = 3810u,
                            Address = "148 Paul Gutierrez St.",
                            Age = 20u,
                            Balance = 37595,
                            Email = "Gregory.King47@gmail.com",
                            FirstName = "Gregory",
                            LastName = "King"
                        },
                        new
                        {
                            AcctNo = 9484u,
                            Address = "385 Gary Rogers St.",
                            Age = 61u,
                            Balance = 17140,
                            Email = "Melissa.Harris729@gmail.com",
                            FirstName = "Melissa",
                            LastName = "Harris"
                        },
                        new
                        {
                            AcctNo = 5067u,
                            Address = "746 Donald Phillips St.",
                            Age = 31u,
                            Balance = 36371,
                            Email = "Margaret.James459@gmail.com",
                            FirstName = "Margaret",
                            LastName = "James"
                        },
                        new
                        {
                            AcctNo = 8364u,
                            Address = "761 Donna Brooks St.",
                            Age = 25u,
                            Balance = 22679,
                            Email = "Jonathan.Hill304@gmail.com",
                            FirstName = "Jonathan",
                            LastName = "Hill"
                        },
                        new
                        {
                            AcctNo = 1880u,
                            Address = "486 Nicholas Morales St.",
                            Age = 57u,
                            Balance = 86011,
                            Email = "Debra.Carter401@gmail.com",
                            FirstName = "Debra",
                            LastName = "Carter"
                        },
                        new
                        {
                            AcctNo = 8359u,
                            Address = "111 Betty Allen St.",
                            Age = 63u,
                            Balance = 30452,
                            Email = "Ashley.Davis583@gmail.com",
                            FirstName = "Ashley",
                            LastName = "Davis"
                        },
                        new
                        {
                            AcctNo = 9087u,
                            Address = "240 Rebecca Reed St.",
                            Age = 85u,
                            Balance = 46501,
                            Email = "Thomas.Ramirez791@gmail.com",
                            FirstName = "Thomas",
                            LastName = "Ramirez"
                        },
                        new
                        {
                            AcctNo = 2293u,
                            Address = "327 Kenneth Wood St.",
                            Age = 56u,
                            Balance = 37258,
                            Email = "Dorothy.Jones130@gmail.com",
                            FirstName = "Dorothy",
                            LastName = "Jones"
                        },
                        new
                        {
                            AcctNo = 2909u,
                            Address = "342 Dennis Martinez St.",
                            Age = 75u,
                            Balance = 39638,
                            Email = "Donna.Lee728@gmail.com",
                            FirstName = "Donna",
                            LastName = "Lee"
                        },
                        new
                        {
                            AcctNo = 1733u,
                            Address = "547 Amy Kim St.",
                            Age = 91u,
                            Balance = 71586,
                            Email = "Linda.Edwards58@gmail.com",
                            FirstName = "Linda",
                            LastName = "Edwards"
                        });
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserHistory", b =>
                {
                    b.Property<int>("transaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("AccountAcctNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoryString")
                        .HasColumnType("TEXT");

                    b.HasKey("transaction");

                    b.HasIndex("AccountAcctNo");

                    b.ToTable("UserHistories");
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "148 Paul Gutierrez St.",
                            Age = 20u,
                            Email = "Gregory.King47@gmail.com",
                            FName = "Gregory",
                            LName = "King",
                            Password = "dC3CVIJPEcJb",
                            PhoneNumber = "+9618062538",
                            Username = "Gregory.King597"
                        },
                        new
                        {
                            Id = 2,
                            Address = "385 Gary Rogers St.",
                            Age = 61u,
                            Email = "Melissa.Harris729@gmail.com",
                            FName = "Melissa",
                            LName = "Harris",
                            Password = "9nkenIBd3ZM8",
                            PhoneNumber = "+9616332483",
                            Username = "Melissa.Harris213"
                        },
                        new
                        {
                            Id = 3,
                            Address = "746 Donald Phillips St.",
                            Age = 31u,
                            Email = "Margaret.James459@gmail.com",
                            FName = "Margaret",
                            LName = "James",
                            Password = "ivVyfXIPH4xY",
                            PhoneNumber = "+9614292723",
                            Username = "Margaret.James225"
                        },
                        new
                        {
                            Id = 4,
                            Address = "761 Donna Brooks St.",
                            Age = 25u,
                            Email = "Jonathan.Hill304@gmail.com",
                            FName = "Jonathan",
                            LName = "Hill",
                            Password = "TUU84hXUwvWr",
                            PhoneNumber = "+9611196142",
                            Username = "Jonathan.Hill664"
                        },
                        new
                        {
                            Id = 5,
                            Address = "486 Nicholas Morales St.",
                            Age = 57u,
                            Email = "Debra.Carter401@gmail.com",
                            FName = "Debra",
                            LName = "Carter",
                            Password = "skcPSEgTewzp",
                            PhoneNumber = "+9613995673",
                            Username = "Debra.Carter108"
                        },
                        new
                        {
                            Id = 6,
                            Address = "111 Betty Allen St.",
                            Age = 63u,
                            Email = "Ashley.Davis583@gmail.com",
                            FName = "Ashley",
                            LName = "Davis",
                            Password = "lDyAvsOwwCHM",
                            PhoneNumber = "+9612583346",
                            Username = "Ashley.Davis790"
                        },
                        new
                        {
                            Id = 7,
                            Address = "240 Rebecca Reed St.",
                            Age = 85u,
                            Email = "Thomas.Ramirez791@gmail.com",
                            FName = "Thomas",
                            LName = "Ramirez",
                            Password = "JYvqzv2ifsRE",
                            PhoneNumber = "+9616091021",
                            Username = "Thomas.Ramirez608"
                        },
                        new
                        {
                            Id = 8,
                            Address = "327 Kenneth Wood St.",
                            Age = 56u,
                            Email = "Dorothy.Jones130@gmail.com",
                            FName = "Dorothy",
                            LName = "Jones",
                            Password = "Q9MhpXVrUi0R",
                            PhoneNumber = "+9617567114",
                            Username = "Dorothy.Jones874"
                        },
                        new
                        {
                            Id = 9,
                            Address = "342 Dennis Martinez St.",
                            Age = 75u,
                            Email = "Donna.Lee728@gmail.com",
                            FName = "Donna",
                            LName = "Lee",
                            Password = "02ZIAi5aOYWl",
                            PhoneNumber = "+9613221345",
                            Username = "Donna.Lee811"
                        },
                        new
                        {
                            Id = 10,
                            Address = "547 Amy Kim St.",
                            Age = 91u,
                            Email = "Linda.Edwards58@gmail.com",
                            FName = "Linda",
                            LName = "Edwards",
                            Password = "fjySQUlH9epg",
                            PhoneNumber = "+9616948348",
                            Username = "Linda.Edwards892"
                        });
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserHistory", b =>
                {
                    b.HasOne("DataTierWebServer.Models.Account", null)
                        .WithMany("History")
                        .HasForeignKey("AccountAcctNo");
                });

            modelBuilder.Entity("DataTierWebServer.Models.Account", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
