// <auto-generated />
using DataTierWebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataTierWebServer.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20240928133247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("DataTierWebServer.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Street Suburb",
                            Email = "Sajib@email.com",
                            Name = "Sajib",
                            Password = "Sajib123",
                            PhoneNumber = 1234567,
                            ProfilePictureUrl = "SomeImage"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 Street Suburb",
                            Email = "Mistry@email.com",
                            Name = "Mistry",
                            Password = "Mistry123",
                            PhoneNumber = 2345678,
                            ProfilePictureUrl = "SomeImage"
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Street Suburb",
                            Email = "Mike@email.com",
                            Name = "Mike",
                            Password = "Mike123",
                            PhoneNumber = 3456789,
                            ProfilePictureUrl = "SomeImage"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
