// <auto-generated />
using DataTierWebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataTierWebServer.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20241013142810_UpdateBankDataModel")]
    partial class UpdateBankDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("DataTierWebServer.Models.Account", b =>
                {
                    b.Property<uint>("AcctNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AcctNo");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AcctNo = 7791u,
                            Address = "128 Carol Kim St.",
                            Age = 91u,
                            Balance = 59523,
                            Email = "Mark.Nelson645@gmail.com",
                            FirstName = "Mark",
                            LastName = "Nelson"
                        },
                        new
                        {
                            AcctNo = 5441u,
                            Address = "77 Sharon Hughes St.",
                            Age = 67u,
                            Balance = 11708,
                            Email = "Mary.Bennett735@gmail.com",
                            FirstName = "Mary",
                            LastName = "Bennett"
                        },
                        new
                        {
                            AcctNo = 6390u,
                            Address = "615 Jack Reyes St.",
                            Age = 75u,
                            Balance = 21411,
                            Email = "Dennis.James492@gmail.com",
                            FirstName = "Dennis",
                            LastName = "James"
                        },
                        new
                        {
                            AcctNo = 8839u,
                            Address = "850 Jennifer Morris St.",
                            Age = 51u,
                            Balance = 28671,
                            Email = "Jason.Brooks488@gmail.com",
                            FirstName = "Jason",
                            LastName = "Brooks"
                        },
                        new
                        {
                            AcctNo = 3937u,
                            Address = "630 Samantha Harris St.",
                            Age = 37u,
                            Balance = 90378,
                            Email = "Deborah.Morris592@gmail.com",
                            FirstName = "Deborah",
                            LastName = "Morris"
                        },
                        new
                        {
                            AcctNo = 7524u,
                            Address = "478 Gary Ruiz St.",
                            Age = 108u,
                            Balance = 50349,
                            Email = "Kevin.Rogers378@gmail.com",
                            FirstName = "Kevin",
                            LastName = "Rogers"
                        },
                        new
                        {
                            AcctNo = 5181u,
                            Address = "577 Kevin Long St.",
                            Age = 98u,
                            Balance = 93063,
                            Email = "Alexander.Thompson801@gmail.com",
                            FirstName = "Alexander",
                            LastName = "Thompson"
                        },
                        new
                        {
                            AcctNo = 5291u,
                            Address = "524 Angela Taylor St.",
                            Age = 108u,
                            Balance = 24207,
                            Email = "Jeffrey.Kelly291@gmail.com",
                            FirstName = "Jeffrey",
                            LastName = "Kelly"
                        },
                        new
                        {
                            AcctNo = 2135u,
                            Address = "658 Richard King St.",
                            Age = 83u,
                            Balance = 34686,
                            Email = "Samantha.James224@gmail.com",
                            FirstName = "Samantha",
                            LastName = "James"
                        },
                        new
                        {
                            AcctNo = 6680u,
                            Address = "103 Betty Williams St.",
                            Age = 107u,
                            Balance = 61961,
                            Email = "Amanda.Davis282@gmail.com",
                            FirstName = "Amanda",
                            LastName = "Davis"
                        });
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserHistory", b =>
                {
                    b.Property<int>("Transaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoryString")
                        .HasColumnType("TEXT");

                    b.HasKey("Transaction");

                    b.HasIndex("AccountId");

                    b.ToTable("UserHistories");

                    b.HasData(
                        new
                        {
                            Transaction = 1,
                            AccountId = 2135u,
                            HistoryString = "Balance updated by -202 on 13/10/2024 10:28:10 PM.  | Old Balance: 35054 ----- New Balance: 34852"
                        },
                        new
                        {
                            Transaction = 2,
                            AccountId = 6680u,
                            HistoryString = "Balance updated by -362 on 13/10/2024 10:28:10 PM.  | Old Balance: 62645 ----- New Balance: 62283"
                        },
                        new
                        {
                            Transaction = 3,
                            AccountId = 6680u,
                            HistoryString = "Balance updated by -322 on 13/10/2024 10:28:10 PM.  | Old Balance: 62283 ----- New Balance: 61961"
                        },
                        new
                        {
                            Transaction = 4,
                            AccountId = 7524u,
                            HistoryString = "Balance updated by 615 on 13/10/2024 10:28:10 PM.  | Old Balance: 49734 ----- New Balance: 50349"
                        },
                        new
                        {
                            Transaction = 5,
                            AccountId = 8839u,
                            HistoryString = "Balance updated by 287 on 13/10/2024 10:28:10 PM.  | Old Balance: 28384 ----- New Balance: 28671"
                        },
                        new
                        {
                            Transaction = 6,
                            AccountId = 2135u,
                            HistoryString = "Balance updated by -166 on 13/10/2024 10:28:10 PM.  | Old Balance: 34852 ----- New Balance: 34686"
                        },
                        new
                        {
                            Transaction = 7,
                            AccountId = 3937u,
                            HistoryString = "Balance updated by 894 on 13/10/2024 10:28:10 PM.  | Old Balance: 89484 ----- New Balance: 90378"
                        },
                        new
                        {
                            Transaction = 8,
                            AccountId = 5181u,
                            HistoryString = "Balance updated by 494 on 13/10/2024 10:28:10 PM.  | Old Balance: 92569 ----- New Balance: 93063"
                        },
                        new
                        {
                            Transaction = 9,
                            AccountId = 7791u,
                            HistoryString = "Balance updated by 170 on 13/10/2024 10:28:10 PM.  | Old Balance: 59353 ----- New Balance: 59523"
                        },
                        new
                        {
                            Transaction = 10,
                            AccountId = 5441u,
                            HistoryString = "Balance updated by -836 on 13/10/2024 10:28:10 PM.  | Old Balance: 12544 ----- New Balance: 11708"
                        });
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "128 Carol Kim St.",
                            Age = 91u,
                            Email = "Mark.Nelson645@gmail.com",
                            FName = "Mark",
                            LName = "Nelson",
                            Password = "2iOUxHxpdMjM",
                            PhoneNumber = "+9618187684",
                            ProfilePictureUrl = "chicken.png",
                            Username = "Mark.Nelson158"
                        },
                        new
                        {
                            Id = 2,
                            Address = "77 Sharon Hughes St.",
                            Age = 67u,
                            Email = "Mary.Bennett735@gmail.com",
                            FName = "Mary",
                            LName = "Bennett",
                            Password = "0Jbj9YMXFVR5",
                            PhoneNumber = "+9616121286",
                            ProfilePictureUrl = "dog.png",
                            Username = "Mary.Bennett209"
                        },
                        new
                        {
                            Id = 3,
                            Address = "615 Jack Reyes St.",
                            Age = 75u,
                            Email = "Dennis.James492@gmail.com",
                            FName = "Dennis",
                            LName = "James",
                            Password = "72w3km4rqSoX",
                            PhoneNumber = "+9619483898",
                            ProfilePictureUrl = "bear.png",
                            Username = "Dennis.James70"
                        },
                        new
                        {
                            Id = 4,
                            Address = "850 Jennifer Morris St.",
                            Age = 51u,
                            Email = "Jason.Brooks488@gmail.com",
                            FName = "Jason",
                            LName = "Brooks",
                            Password = "hOlLQZAFR4id",
                            PhoneNumber = "+9613603453",
                            ProfilePictureUrl = "meerkat.png",
                            Username = "Jason.Brooks824"
                        },
                        new
                        {
                            Id = 5,
                            Address = "630 Samantha Harris St.",
                            Age = 37u,
                            Email = "Deborah.Morris592@gmail.com",
                            FName = "Deborah",
                            LName = "Morris",
                            Password = "wdYfwNxcu3QP",
                            PhoneNumber = "+9617902471",
                            ProfilePictureUrl = "gamer.png",
                            Username = "Deborah.Morris646"
                        },
                        new
                        {
                            Id = 6,
                            Address = "478 Gary Ruiz St.",
                            Age = 108u,
                            Email = "Kevin.Rogers378@gmail.com",
                            FName = "Kevin",
                            LName = "Rogers",
                            Password = "1lxoDUMc8s9y",
                            PhoneNumber = "+9613607148",
                            ProfilePictureUrl = "meerkat.png",
                            Username = "Kevin.Rogers213"
                        },
                        new
                        {
                            Id = 7,
                            Address = "577 Kevin Long St.",
                            Age = 98u,
                            Email = "Alexander.Thompson801@gmail.com",
                            FName = "Alexander",
                            LName = "Thompson",
                            Password = "znVfW4ZbvJkh",
                            PhoneNumber = "+9618815422",
                            ProfilePictureUrl = "rabbit.png",
                            Username = "Alexander.Thompson443"
                        },
                        new
                        {
                            Id = 8,
                            Address = "524 Angela Taylor St.",
                            Age = 108u,
                            Email = "Jeffrey.Kelly291@gmail.com",
                            FName = "Jeffrey",
                            LName = "Kelly",
                            Password = "rwYcV2CzTbn7",
                            PhoneNumber = "+9612225898",
                            ProfilePictureUrl = "astronaut.png",
                            Username = "Jeffrey.Kelly436"
                        },
                        new
                        {
                            Id = 9,
                            Address = "658 Richard King St.",
                            Age = 83u,
                            Email = "Samantha.James224@gmail.com",
                            FName = "Samantha",
                            LName = "James",
                            Password = "9OSuTPIIbKdn",
                            PhoneNumber = "+9616016068",
                            ProfilePictureUrl = "meerkat.png",
                            Username = "Samantha.James284"
                        },
                        new
                        {
                            Id = 10,
                            Address = "103 Betty Williams St.",
                            Age = 107u,
                            Email = "Amanda.Davis282@gmail.com",
                            FName = "Amanda",
                            LName = "Davis",
                            Password = "iBTr2tObfkbY",
                            PhoneNumber = "+9615967562",
                            ProfilePictureUrl = "bear.png",
                            Username = "Amanda.Davis334"
                        });
                });

            modelBuilder.Entity("DataTierWebServer.Models.UserHistory", b =>
                {
                    b.HasOne("DataTierWebServer.Models.Account", null)
                        .WithMany("History")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataTierWebServer.Models.Account", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
